import urllib.parse
from typing import Optional
from app.models.review_models import InlineCommentProposal, BreakingChangeAlert


class MultiToolFixBuilder:
    """Formats review comments with GitHub suggestions, deep links,

    and copyable CLI prompts for Claude Code, Codex, and Antigravity CLI.
    """

    @classmethod
    def enrich_comment_proposal(
        cls,
        proposal: InlineCommentProposal,
        repo_name: str,
        pr_number: int,
    ) -> InlineCommentProposal:
        """Enriches an InlineCommentProposal with copyable CLI commands

        and preloaded web links.
        """
        # Clean prompt message
        clean_issue = proposal.issue_title.replace('"', '\\"')
        clean_desc = proposal.description.replace('"', '\\"')

        # 1. Antigravity CLI (agy) command
        proposal.agy_command = (
            f'agy "Fix issue in {proposal.file_path} at line {proposal.line_number}: '
            f'{clean_issue}. Detail: {clean_desc}"'
        )

        # 2. Claude Code CLI command
        proposal.claude_code_command = (
            f'claude "Fix issue in {proposal.file_path} at line {proposal.line_number}: '
            f'{clean_issue}"'
        )

        # 3. Codex / ChatGPT Prompt
        proposal.codex_prompt = (
            f"Fix issue in `{proposal.file_path}` at line {proposal.line_number}.\n"
            f"Problem: {proposal.issue_title}\n"
            f"Description: {proposal.description}\n"
        )
        if proposal.suggested_replacement:
            proposal.codex_prompt += (
                f"Proposed change:\n```\n{proposal.suggested_replacement}\n```"
            )

        # 4. Web URLs with preloaded prompts
        encoded_prompt = urllib.parse.quote(
            f"Fix issue in PR #{pr_number} ({repo_name}): {proposal.file_path}:{proposal.line_number}\n"
            f"{proposal.issue_title}\n{proposal.description}"
        )
        proposal.deep_link_claude = f"https://claude.ai/new?q={encoded_prompt}"
        proposal.deep_link_codex = f"https://chatgpt.com/?q={encoded_prompt}"

        return proposal

    @classmethod
    def format_github_review_comment(cls, proposal: InlineCommentProposal) -> str:
        """Renders the comprehensive markdown body for an inline PR review comment."""
        md = []
        md.append(f"### ⚠️ {proposal.issue_title}\n")
        md.append(f"{proposal.description}\n")

        # Option 1: Direct GitHub Suggestion block
        if proposal.suggested_replacement:
            md.append("#### 1️⃣ Apply Direct Fix (GitHub One-Click Suggestion)")
            md.append("```suggestion")
            md.append(proposal.suggested_replacement.rstrip("\n"))
            md.append("```\n")

        # Option 2: Preloaded App Buttons
        md.append("#### 2️⃣ Fix in AI Tools (Preloaded Prompt)")
        md.append(
            f"[![Fix in Claude Code](https://img.shields.io/badge/Fix%20in-Claude%20Code-7C3AED?logo=anthropic)]({proposal.deep_link_claude}) "
            f"[![Fix in Codex](https://img.shields.io/badge/Fix%20in-Codex-10A37F?logo=openai)]({proposal.deep_link_codex})"
        )
        md.append("")

        # Option 3: Copyable CLI commands
        md.append("#### 3️⃣ Or Copy Terminal Prompt to Run Locally")
        md.append("**Antigravity CLI (`agy`):**")
        md.append(f"```bash\n{proposal.agy_command}\n```")
        md.append("**Claude Code CLI (`claude`):**")
        md.append(f"```bash\n{proposal.claude_code_command}\n```")

        md.append(
            "\n---\n*Generated by [auto-code-reviewer](https://github.com/your-org/auto-code-reviewer) powered by OpenHands.*"
        )
        return "\n".join(md)

    @classmethod
    def format_breaking_change_section(
        cls, alerts: list[BreakingChangeAlert]
    ) -> str:
        """Renders breaking change warnings into markdown for the PR description."""
        if not alerts:
            return ""

        md = ["### 🚨 Cross-File Breaking Change Warnings\n"]
        for alert in alerts:
            md.append(f"#### ⚠️ `{alert.symbol_name}` in `{alert.file_path}`")
            md.append(f"{alert.description}\n")
            if alert.affected_callers:
                md.append("**Potential impact on dependent callers:**")
                for caller in alert.affected_callers:
                    md.append(f"- `{caller}`")
                md.append("")
        return "\n".join(md)
